# Generated by Django 5.1.6 on 2025-04-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_supplies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='inv_manage',
            new_name='inv_manage_id',
        ),
    ]
